[package]
name = "shared"
version = "0.1.0"
authors = ["Aaron Housh <dispersias@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
coi = { git = "https://github.com/Nashenas88/coi" }
config = "0.10"

[features]
dev = []
prod = []
